[package]
name = "braillegl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
device_query = "0.2.8"
lodepng = "3.4.6"
float-ord = "0.3.2"
